import type { Locale } from '@/lib/i18n';
import { pluralRu } from '@/lib/i18n';

const en = {
  appName: 'PingoGo',
  tabSites: 'Sites',
  tabIncidents: 'Incidents',
  tabSettings: 'Settings',
  loading: 'Loading…',
  retry: 'Retry',
  notInTelegram: 'Open this page from the PingoGo bot in Telegram.',
  notInTelegramHint: 'This is the Telegram Mini App version of PingoGo. In a browser, use the regular dashboard.',
  openDashboard: 'Open dashboard',
  // Login
  loginTitle: 'Sign in to PingoGo',
  loginBody: 'Use the email and password of your PingoGo account. This Telegram will be linked to it for alerts.',
  email: 'Email',
  password: 'Password',
  signIn: 'Sign in and link Telegram',
  signingIn: 'Signing in…',
  noAccount: 'No account yet? Register on the website first.',
  register: 'Create account',
  // Sites
  sitesTitle: 'Your sites',
  sitesEmpty: 'No sites yet. Add the first one — checks start immediately.',
  addSite: 'Add site',
  statusUp: 'Up',
  statusDown: 'Down',
  statusUnknown: 'Checking',
  statusPaused: 'Paused',
  summary: (up: number, down: number, paused: number) => `${up} up · ${down} down · ${paused} paused`,
  // Site
  uptime24: '24h uptime',
  uptime7: '7 days',
  uptime30: '30 days',
  response: 'Response',
  http: 'HTTP',
  lastCheck: 'Last check',
  lastOutage: 'Last outage',
  interval: 'Interval',
  never: 'never',
  notYet: 'not yet',
  everyMin: (n: number) => `every ${n} min`,
  ssl: 'SSL certificate',
  domain: 'Domain',
  dns: 'DNS records',
  expired: 'expired',
  daysLeft: (n: number) => `${n} ${n === 1 ? 'day' : 'days'} left`,
  issuer: 'Issuer',
  registrar: 'Registrar',
  latencyChart: 'Response time, last 24h',
  noData: 'No data yet',
  checkNow: 'Check now',
  checking: 'Checking…',
  checkQueued: 'Check started. Pull down to refresh in a few seconds.',
  pause: 'Pause',
  resume: 'Resume',
  delete: 'Delete site',
  confirmDelete: (host: string) => `Delete ${host}? All history will be removed.`,
  deleted: 'Site deleted.',
  siteIncidents: 'Incidents for this site',
  // Add
  addTitle: 'Add a site',
  addBody: 'Paste the address. PingoGo checks HTTP, SSL, DNS and domain expiry.',
  urlPlaceholder: 'https://example.com',
  adding: 'Adding…',
  added: 'Site added. The first check is running.',
  // Incidents
  incidentsTitle: 'Incidents',
  incidentsEmpty: 'No incidents. All quiet.',
  ongoing: 'Ongoing',
  resolved: 'Resolved',
  duration: 'Duration',
  started: 'Started',
  // Settings
  settingsTitle: 'Settings',
  notifications: 'Notifications',
  prefWebsiteDowntime: 'Site down',
  prefWebsiteRecovery: 'Site recovered',
  prefSslExpiration: 'SSL expiring',
  prefDomainExpiration: 'Domain expiring',
  prefDnsChanges: 'DNS changes',
  sendTest: 'Send test alert',
  testSent: 'Test alert sent to this chat.',
  language: 'Language',
  account: 'Account',
  connected: 'Connected',
  plan: 'Plan',
  currentPlan: 'Current plan',
  manage: 'Manage',
  // Plan
  planTitle: 'Plan & limits',
  sitesUsed: 'Active sites',
  minInterval: 'Min. check interval',
  history: 'History',
  historyDays: (n: number) => `${n} days`,
  minutes: (n: number) => `${n} min`,
  sitesCount: (n: number) => `${n} ${n === 1 ? 'site' : 'sites'}`,
  perMonth: '/mo',
  upgrade: 'Upgrade',
  current: 'Current',
  manageBilling: 'Manage billing',
  billingUnavailable: 'Payments are not configured yet. Open the dashboard to change your plan.',
  openingCheckout: 'Opening payment…',
  // Misc
  error: 'Something went wrong.',
  saved: 'Saved',
};

export type TgStrings = typeof en;

const ru: TgStrings = {
  appName: 'PingoGo',
  tabSites: 'Сайты',
  tabIncidents: 'Инциденты',
  tabSettings: 'Настройки',
  loading: 'Загрузка…',
  retry: 'Повторить',
  notInTelegram: 'Откройте эту страницу из бота PingoGo в Telegram.',
  notInTelegramHint: 'Это версия PingoGo для Telegram Mini App. В браузере используйте обычный дашборд.',
  openDashboard: 'Открыть дашборд',
  loginTitle: 'Вход в PingoGo',
  loginBody: 'Введите email и пароль от аккаунта PingoGo. Этот Telegram будет привязан к нему для уведомлений.',
  email: 'Email',
  password: 'Пароль',
  signIn: 'Войти и привязать Telegram',
  signingIn: 'Входим…',
  noAccount: 'Ещё нет аккаунта? Сначала зарегистрируйтесь на сайте.',
  register: 'Создать аккаунт',
  sitesTitle: 'Ваши сайты',
  sitesEmpty: 'Сайтов пока нет. Добавьте первый — проверки начнутся сразу.',
  addSite: 'Добавить сайт',
  statusUp: 'Работает',
  statusDown: 'Недоступен',
  statusUnknown: 'Проверяем',
  statusPaused: 'На паузе',
  summary: (up: number, down: number, paused: number) => `${up} работают · ${down} упали · ${paused} на паузе`,
  uptime24: 'Аптайм 24ч',
  uptime7: '7 дней',
  uptime30: '30 дней',
  response: 'Ответ',
  http: 'HTTP',
  lastCheck: 'Последняя проверка',
  lastOutage: 'Последний сбой',
  interval: 'Интервал',
  never: 'не было',
  notYet: 'ещё нет',
  everyMin: (n: number) => `каждые ${n} мин`,
  ssl: 'SSL-сертификат',
  domain: 'Домен',
  dns: 'DNS-записи',
  expired: 'истёк',
  daysLeft: (n: number) => `осталось ${n} ${pluralRu(n, 'день', 'дня', 'дней')}`,
  issuer: 'Издатель',
  registrar: 'Регистратор',
  latencyChart: 'Время ответа за 24 часа',
  noData: 'Данных пока нет',
  checkNow: 'Проверить сейчас',
  checking: 'Проверяем…',
  checkQueued: 'Проверка запущена. Обновите экран через несколько секунд.',
  pause: 'Пауза',
  resume: 'Возобновить',
  delete: 'Удалить сайт',
  confirmDelete: (host: string) => `Удалить ${host}? Вся история будет удалена.`,
  deleted: 'Сайт удалён.',
  siteIncidents: 'Инциденты этого сайта',
  addTitle: 'Добавить сайт',
  addBody: 'Вставьте адрес. PingoGo проверит HTTP, SSL, DNS и срок домена.',
  urlPlaceholder: 'https://example.com',
  adding: 'Добавляем…',
  added: 'Сайт добавлен. Первая проверка уже идёт.',
  incidentsTitle: 'Инциденты',
  incidentsEmpty: 'Инцидентов нет. Всё спокойно.',
  ongoing: 'Продолжается',
  resolved: 'Решён',
  duration: 'Длительность',
  started: 'Начало',
  settingsTitle: 'Настройки',
  notifications: 'Уведомления',
  prefWebsiteDowntime: 'Сайт упал',
  prefWebsiteRecovery: 'Сайт восстановился',
  prefSslExpiration: 'Истекает SSL',
  prefDomainExpiration: 'Истекает домен',
  prefDnsChanges: 'Изменения DNS',
  sendTest: 'Тестовое уведомление',
  testSent: 'Тестовое уведомление отправлено в этот чат.',
  language: 'Язык',
  account: 'Аккаунт',
  connected: 'Подключён',
  plan: 'Тариф',
  currentPlan: 'Текущий тариф',
  manage: 'Управлять',
  planTitle: 'Тариф и лимиты',
  sitesUsed: 'Активных сайтов',
  minInterval: 'Мин. интервал проверки',
  history: 'История',
  historyDays: (n: number) => `${n} дн.`,
  minutes: (n: number) => `${n} мин`,
  sitesCount: (n: number) => `${n} ${pluralRu(n, 'сайт', 'сайта', 'сайтов')}`,
  perMonth: '/мес',
  upgrade: 'Перейти',
  current: 'Текущий',
  manageBilling: 'Управление оплатой',
  billingUnavailable: 'Оплата пока не настроена. Откройте дашборд, чтобы сменить тариф.',
  openingCheckout: 'Открываем оплату…',
  error: 'Что-то пошло не так.',
  saved: 'Сохранено',
};

export function tgStrings(locale: Locale): TgStrings {
  return locale === 'ru' ? ru : en;
}
